# Generated by Django 3.2.3 on 2022-01-27 11:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sewing_site', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_of_post',
            field=models.DateField(default=datetime.date.today, verbose_name='Дата статьи'),
        ),
    ]
