# Generated by Django 3.2.3 on 2022-01-27 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sewing_site', '0002_alter_post_date_of_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postimage',
            name='text_of_image',
            field=models.TextField(blank=True, verbose_name='Текст к изображению'),
        ),
        migrations.AlterField(
            model_name='postimage',
            name='title',
            field=models.CharField(blank=True, max_length=100, verbose_name='Подпись к изображению'),
        ),
    ]
