# Generated by Django 3.2.3 on 2022-01-29 10:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sewing_site', '0003_auto_20220127_2159'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_of_preview_master_class', models.ImageField(upload_to='photo_of_preview_masterclass/', verbose_name='Изображение заставки мастеркласс')),
                ('date_of_master_class', models.DateField(default=datetime.date.today, verbose_name='Дата публикации')),
                ('title_of_master_class', models.CharField(max_length=64, verbose_name='Название мастер класса')),
                ('text_of_master_class', models.TextField(verbose_name='Текст к изображению')),
            ],
            options={
                'verbose_name': 'Мастер-класс',
                'verbose_name_plural': 'Мастер-классы',
            },
        ),
        migrations.DeleteModel(
            name='PostImage',
        ),
    ]
